from django.urls import re_path as url # from django.conf.urls import url
from django.urls import path, include
from .views import (
    RolesListApiView,
    RolesDetailApiView,
    PersionsListApiView,
    PersionsDetailApiView,
    Report1ListApiView,
    Report1DetailApiView,
    Report2ListApiView,
    Report2DetailApiView,
    StationsListApiView,
    StationsDetailApiView,
    UsersListApiView,
    UsersDetailApiView,
    LocationListApiView,
    LocationDetailApiView,
    form1ListApiView,
    form1DetailApiView,
    form2ListApiView,
    form2DetailApiView,
    NonConfirmationListApiView,
    NonConfirmationDetailApiView,
)

urlpatterns = [
    path('api', RolesListApiView.as_view()),
    path('api/<int:todo_id>/', RolesDetailApiView.as_view()),
    path('api', PersionsListApiView.as_view()),
    path('api/<int:todo_id>/', PersionsDetailApiView.as_view()),
    path('api', Report1ListApiView.as_view()),
    path('api/<int:todo_id>/', Report1DetailApiView.as_view()),
    path('api', Report2ListApiView.as_view()),
    path('api/<int:todo_id>/', Report2DetailApiView.as_view()),
    path('api', StationsListApiView.as_view()),
    path('api/<int:todo_id>/', StationsDetailApiView.as_view()),
    path('api', UsersListApiView.as_view()),
    path('api/<int:todo_id>/', UsersDetailApiView.as_view()),
    path('api', LocationListApiView.as_view()),
    path('api/<int:todo_id>/', LocationDetailApiView.as_view()),
    path('api', form1ListApiView.as_view()),
    path('api/<int:todo_id>/', form1DetailApiView.as_view()),
    path('api', form2ListApiView.as_view()),
    path('api/<int:todo_id>/', form2DetailApiView.as_view()),
    path('api', NonConfirmationListApiView.as_view()),
    path('api/<int:todo_id>/', NonConfirmationDetailApiView.as_view()),
]