# Generated by Django 4.0.5 on 2022-06-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_roles_createtime_roles_expiredate_roles_roletype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persions',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(blank=True, max_length=200)),
                ('lastName', models.CharField(blank=True, max_length=200)),
                ('accuption', models.CharField(blank=True, max_length=200)),
                ('personelNumber', models.CharField(blank=True, max_length=200)),
                ('phoneNumber', models.CharField(blank=True, max_length=200)),
                ('eMailAddress', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
