# Generated by Django 4.0.5 on 2022-06-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0004_persions_managerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report1',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('parentID', models.IntegerField(null=True)),
                ('stationID', models.IntegerField(null=True)),
                ('locationID', models.IntegerField(null=True)),
                ('userID', models.IntegerField(null=True)),
                ('creationDate', models.DateTimeField(blank=True)),
                ('field_1', models.CharField(blank=True, max_length=200)),
                ('field_n', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
