# Generated by Django 4.0.5 on 2022-06-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0005_report1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report2',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('parentID', models.IntegerField(null=True)),
                ('stationID', models.IntegerField(null=True)),
                ('locationID', models.IntegerField(null=True)),
                ('userID', models.IntegerField(null=True)),
                ('creationDate', models.DateTimeField(blank=True)),
                ('field_1', models.IntegerField(null=True)),
                ('field_n', models.IntegerField(null=True)),
            ],
        ),
    ]
