# Generated by Django 4.0.5 on 2022-06-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0006_report2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('rName', models.CharField(blank=True, max_length=200)),
                ('parentID', models.IntegerField(null=True)),
                ('description', models.IntegerField(null=True)),
                ('EmergencyContact', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('stationID', models.CharField(blank=True, max_length=200)),
                ('personlnCharge', models.IntegerField(null=True)),
                ('Location', models.CharField(blank=True, max_length=200)),
                ('gpsLocation', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('familyName', models.CharField(blank=True, max_length=200)),
                ('roleID', models.IntegerField(null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=200)),
                ('eMailAddress', models.EmailField(blank=True, max_length=254)),
                ('expireDate', models.DateTimeField(null=True)),
            ],
        ),
    ]
