# Generated by Django 4.0.5 on 2022-06-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0008_form1'),
    ]

    operations = [
        migrations.CreateModel(
            name='form2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.CharField(blank=True, max_length=50)),
                ('Region', models.CharField(blank=True, max_length=200)),
                ('StationName', models.CharField(blank=True, max_length=200)),
                ('distance1', models.FloatField(null=True, verbose_name='(فاصله بین دو نقطه(متر')),
                ('distance2', models.FloatField(null=True, verbose_name='(فاصله بین دو نقطه(متر')),
                ('distance3', models.FloatField(null=True, verbose_name='(فاصله بین دو نقطه(متر')),
                ('ScrollingTime1', models.IntegerField(null=True, verbose_name='(زمان پیمایش(ثانیه')),
                ('ScrollingTime2', models.IntegerField(null=True, verbose_name='(زمان پیمایش(ثانیه')),
                ('ScrollingTime3', models.IntegerField(null=True, verbose_name='(زمان پیمایش(ثانیه')),
                ('WaterHeight1', models.FloatField(null=True, verbose_name='(ارتفاع آب(متر')),
                ('WaterHeight2', models.FloatField(null=True, verbose_name='(ارتفاع آب(متر')),
                ('WaterHeight3', models.FloatField(null=True, verbose_name='(ارتفاع آب(متر')),
                ('ChannelDepth', models.FloatField(null=True, verbose_name='(عمق کانال(متر')),
                ('ChannelWidth', models.FloatField(null=True, verbose_name='(عرض کانال(متر')),
                ('ReportDate', models.DateTimeField(null=True, verbose_name='تاریخ تهیه گزارش')),
                ('Responsible1Name', models.CharField(blank=True, max_length=200, verbose_name='نام مسئول تهیه گزارش')),
                ('Responsible1Signature', models.ImageField(upload_to='images/', verbose_name='امضاء مسئول تهیه گزارش')),
                ('Responsible2Name', models.CharField(blank=True, max_length=200, verbose_name='نام مسئول تایید گزارش')),
                ('Responsible2Signature', models.ImageField(upload_to='images/', verbose_name='امضاء مسئول تایید گزارش')),
            ],
        ),
    ]
