# Generated by Django 4.0.5 on 2022-06-29 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0009_form2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
