# Generated by Django 4.0.5 on 2022-08-01 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_api', '0011_nonconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form2',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nonconfirmation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Responsible1Signature',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='امضاء مسئول تهیه گزارش'),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Responsible2Signature',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='امضاء مسئول تایید گزارش'),
        ),
    ]
