# Generated by Django 4.0.5 on 2022-08-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0012_form1_user_form2_user_nonconfirmation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='Month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='form1',
            name='ReportDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تهیه گزارش'),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Responsible1Name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام مسئول تهیه گزارش'),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Responsible1Signature',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='امضاء مسئول تهیه گزارش'),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Responsible2Name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام مسئول تایید گزارش'),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Responsible2Signature',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='امضاء مسئول تایید گزارش'),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Row1',
            field=models.TextField(blank=True, null=True, verbose_name='قفل بودن درب محوطه ایستگاه'),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Row10',
            field=models.TextField(blank=True, null=True, verbose_name='سایر موارد - موارد اعلامی از سوی سازمان'),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Row2',
            field=models.TextField(blank=True, null=True, verbose_name='قفل بودن درب جعبه تجهیزات'),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Row3',
            field=models.TextField(blank=True, null=True, verbose_name='عدم وجود آب، برف، علوفه، زباله، نخاله و... در محوطه ایستگاه و اطراف'),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Row4',
            field=models.TextField(blank=True, null=True, verbose_name='عدم گسترش پوشش گیاهی موجود (درختان و ..). در محوطه و اطراف ایستگاه'),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Row5',
            field=models.TextField(blank=True, null=True, verbose_name='عدم انجام عملیات عمرانی در محوطه ایستگاه و اطراف'),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Row6',
            field=models.TextField(blank=True, null=True, verbose_name='عدم وجود هرگونه مانع و تجهیزات در مجاورت ایستگاه تا فاصله  2متری'),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Row7',
            field=models.TextField(blank=True, null=True, verbose_name='کنترل وضعیت برق ایستگاه'),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Row8',
            field=models.TextField(blank=True, null=True, verbose_name='وضعیت سیستمهای ارتباطی و آنتن خارجی'),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Row9',
            field=models.TextField(blank=True, null=True, verbose_name='تعداد و تاریخ مراجعه اضطراری به ایستگاه'),
        ),
        migrations.AlterField(
            model_name='form1',
            name='StationName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
