# Generated by Django 4.0.5 on 2022-08-11 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0014_alter_form2_channeldepth_alter_form2_channelwidth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='ReportDate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='تاریخ تهیه گزارش'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='ReportDate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='تاریخ تهیه گزارش'),
        ),
    ]
