# Generated by Django 4.0.5 on 2022-08-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0015_alter_form1_reportdate_alter_form2_reportdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form2',
            name='ChannelDepth',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='(عمق کانال(متر'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='ChannelWidth',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='(عرض کانال(متر'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='ScrollingTime1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='(زمان پیمایش(ثانیه'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='ScrollingTime2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='(زمان پیمایش(ثانیه'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='ScrollingTime3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='(زمان پیمایش(ثانیه'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='WaterHeight1',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='(ارتفاع آب(متر'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='WaterHeight2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='(ارتفاع آب(متر'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='WaterHeight3',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='(ارتفاع آب(متر'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='distance1',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='(فاصله بین دو نقطه(متر'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='distance2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='(فاصله بین دو نقطه(متر'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='distance3',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='(فاصله بین دو نقطه(متر'),
        ),
    ]
