# Generated by Django 4.0.5 on 2022-08-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0016_alter_form2_channeldepth_alter_form2_channelwidth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form2',
            name='ChannelDepth',
            field=models.FloatField(default=0, verbose_name='(عمق کانال(متر'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='ChannelWidth',
            field=models.FloatField(default=0, verbose_name='(عرض کانال(متر'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='ScrollingTime1',
            field=models.IntegerField(default=0, verbose_name='(زمان پیمایش(ثانیه'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='ScrollingTime2',
            field=models.IntegerField(default=0, verbose_name='(زمان پیمایش(ثانیه'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='ScrollingTime3',
            field=models.IntegerField(default=0, verbose_name='(زمان پیمایش(ثانیه'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='WaterHeight1',
            field=models.FloatField(default=0, verbose_name='(ارتفاع آب(متر'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='WaterHeight2',
            field=models.FloatField(default=0, verbose_name='(ارتفاع آب(متر'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='WaterHeight3',
            field=models.FloatField(default=0, verbose_name='(ارتفاع آب(متر'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='distance1',
            field=models.FloatField(default=0, verbose_name='(فاصله بین دو نقطه(متر'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='distance2',
            field=models.FloatField(default=0, verbose_name='(فاصله بین دو نقطه(متر'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='distance3',
            field=models.FloatField(default=0, verbose_name='(فاصله بین دو نقطه(متر'),
        ),
    ]
