# Generated by Django 4.0.5 on 2022-08-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0017_alter_form2_channeldepth_alter_form2_channelwidth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='Responsible1Signature',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='امضاء مسئول تهیه گزارش'),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Responsible2Signature',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='امضاء مسئول تایید گزارش'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='Responsible1Signature',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='امضاء مسئول تهیه گزارش'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='Responsible2Signature',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='امضاء مسئول تایید گزارش'),
        ),
    ]
