# Generated by Django 4.0.5 on 2022-08-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0018_alter_form1_responsible1signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='Responsible1Signature',
            field=models.FileField(blank=True, null=True, upload_to='images', verbose_name='امضاء مسئول تهیه گزارش'),
        ),
    ]
