# Generated by Django 4.0.5 on 2022-08-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0019_alter_form1_responsible1signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='Responsible1Signature',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='امضاء مسئول تهیه گزارش'),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Responsible2Signature',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='امضاء مسئول تایید گزارش'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='Responsible1Signature',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='امضاء مسئول تهیه گزارش'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='Responsible2Signature',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='امضاء مسئول تایید گزارش'),
        ),
    ]
