# Generated by Django 4.0.5 on 2022-08-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0023_form3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تهیه گزارش'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تهیه گزارش'),
        ),
        migrations.AlterField(
            model_name='form3',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تهیه گزارش'),
        ),
    ]
