# Generated by Django 4.0.5 on 2022-08-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0024_alter_form1_report_date_alter_form2_report_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ تهیه گزارش'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ تهیه گزارش'),
        ),
        migrations.AlterField(
            model_name='form3',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ تهیه گزارش'),
        ),
    ]
